# Generated by Django 2.2.2 on 2019-06-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='weather',
        ),
    ]
